;; -*- mode: emacs-lisp -*-
(when (memq window-system '(mac ns))
  (exec-path-from-shell-initialize))
(when (spacemacs/system-is-mac)
  (when (display-graphic-p)
    ;; (set-frame-size (selected-frame) 200 48)
    ;; (add-to-list 'default-frame-alist '(width . 150))
    ;; (add-to-list 'default-frame-alist '(height . 48))
    ;; (modify-frame-parameters (selected-frame) '((alpha . 95)))

    (global-set-key (kbd "s-<right>") 'move-end-of-line)
    ;; (global-set-key (kbd "s-<left>") 'move-beginning-of-line)
    (global-set-key (kbd "s-<left>") 'back-to-indentation)
    (global-set-key (kbd "s-<up>") 'beginning-of-buffer)
    (global-set-key (kbd "s-<down>") 'end-of-buffer)
    (global-set-key (kbd "s-/") 'comment-or-uncomment-region)
    (global-set-key (kbd "M-<left>") 'backward-word)
    (global-set-key (kbd "M-<right>") 'forward-word)
    ))
