;; -*- mode: emacs-lisp -*-
(setq show-trailing-whitespace t)
(setq deft-directory "~/Dropbox/Notes")
(setq deft-extensions '("org" "md" "txt", "sh"))
(setq org-directory "~/Dropbox/Notes/org")
(setq-default indent-tabs-mode nil)
(setq-default global-auto-highlight-symbol-mode nil)
(setq tab-width 4)
(global-linum-mode 1)
(setq-default cursor-type 'box)
